### ISSUE TITLE
Make the horizontal layer responsive

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tinypounder#8]
in shorter screens, inputs and buttons are kept in 1 line and we do not see the ADD button on a mac screen

![http://i.imgur.com/2gi37pc.png](http://i.imgur.com/2gi37pc.png)

**Comment by anthonydahanne** [comment]
what do you mean ? what should be done ?

**Comment by mathieucarbou** [comment]
if you reduce the screen, the fields should wrap, not overflow. There's some responsive options in Vaadin I saw.
